spring:
  graphql:
    graphiql:
      enabled:
        true
  application:
    name: club_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/random_walk_postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      schema: club
  flyway:
    locations: ${FLYWAY_MIGRATION_LOCATIONS:classpath:db/local_migration,classpath:db/migration}
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:http://localhost:8081}
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: "club-service"
  jpa:
    show-sql: ${LOGGING_SHOW_JPA_QUERIES:true}
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
      auto-startup: false
logging:
  level:
    ru.random.walk.chat_service: ${GENERAL_LOGGING_LEVEL:DEBUG}
    org.hibernate.orm.jdbc.bind: ${LOGGING_SHOW_BINDING_JPA_VALUES_LEVEL:TRACE}
outbox:
  job:
    startIntervalInSeconds: 5
storage:
  endpoint: ${STORAGE_ENDPOINT}
  bucketName: ${STORAGE_BUCKET_NAME}
  accessKey: ${STORAGE_ACCESS_KEY}
  secretKey: ${STORAGE_SECRET_KEY}
  region: ${STORAGE_REGION}
  temporaryUrlTtlInMinutes: 1
  servicePath: club-service
rate-limiter:
#  period-duration описание - где P это дата, а T это время
#  # 12 часов
#  rate-limiter.uploadPhotoForClubRateLimiter.period-duration=PT12H
#
#  # 1 день
#  rate-limiter.uploadPhotoForClubRateLimiter.period-duration=P1D
#
#  # 2 дня и 3 часа
#  rate-limiter.uploadPhotoForClubRateLimiter.period-duration=P2DT3H
#
#  # 1 неделя (7 дней)
#  rate-limiter.uploadPhotoForClubRateLimiter.period-duration=P7D
#
#  # 1 месяц и 15 минут
#  rate-limiter.uploadPhotoForClubRateLimiter.period-duration=P1MT15M
#
#  # 2 года, 3 месяца, 4 дня, 5 часов, 6 минут и 7 секунд
#  rate-limiter.uploadPhotoForClubRateLimiter.period-duration=P2Y3M4DT5H6M7S
  uploadPhotoForClubRateLimiter:
    period-duration: PT30S
  getClubPhotoUserRateLimiter:
    period-duration: PT15S